title: 모두의티켓
description: 공지사항 페이지
baseurl: ""
url: "https://mabujangpcs-cpu.github.io"

collections:
  notices:
    output: true
    permalink: /notices/:path/

# 마크다운 설정 추가
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 플러그인 설정 추가  
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - kramdown-parser-gfm

defaults:
  - scope:
      path: ""
      type: "notices"
    values:
      layout: "notice"
